config/routes.rb
Rails.application.routes.draw do

  get 'feed' => 'conversations#feed'

  resources :conversations, only: [:create, :index] do
    get 'comments'
    post 'comment'
    get 'like_toggle'
    collection do
      get 'home'
      get 'top'
    end
  end

  root :to => 'users#index'

  devise_for :users, :controllers => { :confirmations => 'confirmations', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }

  devise_scope :user do
    get 'account' => 'registrations#edit'
    get "signout", to: "devise/sessions#destroy"
  end

  resources :users, only: [:index, :show] do
    get 'conversations' => 'conversations#user_feed'
    member do
      get 'tester'
      get 'new_message'
      post 'post_message'
      get  'block'
      post 'post_location_update'
    end
    collection do
      get 'update_location'
    end
  end

  get 'how_it_works' => 'static#how_it_works'
  get 'hire_me' => 'static#hire_me'
  get 'contact' => 'static#contact'
  
  get 'omniauth_callbacks/facebook'
  get 'omniauth_callbacks/linkedin'
  get 'omniauth_callbacks/google'

end

app/views/findgoplayers.com/_edit_user_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  <%= f.hidden_field :loc_string %>
  <%= f.hidden_field :locality %>
  <%= f.hidden_field :admin_area_1 %>
  <%= f.hidden_field :country %>


  <section>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12">
        <div class="bs-example-tabs">
          <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a data-toggle="tab" href="#name_rank">Basic</a></li>
            <li><a data-toggle="tab" href="#profile">Profile</a></li>
            <li><a data-toggle="tab" href="#avatar">Avatar</a></li>
            <li><a data-toggle="tab" href="#email">Email</a></li>
            <li><a data-toggle="tab" href="#password">Password</a></li>
            <li><a data-toggle="tab" href="#notifications">Notifications</a></li>
          </ul>

          <div class="tab-content" id="myTabContent">

            <div id="name_rank" class="tab-pane fade in active">
              <div class="form-group">
                <%= f.label :type %>
                <div class="input-group">
                  <label class="radio-inline"> 
                    <%= f.radio_button :user_type, "0" %>
                    Player</label>
                  <label class="radio-inline"> 
                    <%= f.radio_button :user_type, "1" %>
                    Go Club</label>
                </div><!-- /input-group -->
              </div>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :nickname, { class: 'form-control'} %>
              </div>
              <div class="form-group" id='user_rank' 
                <% if current_user.club? %> style="display:none" <% end %> 
                >
                <%= f.label :rank %>
                <%= f.select(:rank, @ranks, { class: 'form-control'}) %>
              </div>
              <div class="form-group" id='club_url'
                <% if current_user.player? %> style="display:none" <% end %> 
                >
                <%= f.label :club_url %>
                <%= f.text_field(:url, { class: 'form-control'}) %>
              </div>

            </div>

            <div id="profile" class="tab-pane fade">
              <div class="form-group">
                <%= f.label :profile %>
                <%= f.text_area :blurb, { rows: 5, class: 'form-control'} %>
              </div>
            </div>

            <div id="avatar" class="tab-pane fade">
              <div class="form-group">
                <%= f.label :avatar %>
                <%= image_tag avatar_url(current_user) %>
              </div>
              <span>Don't have an avatar?  Set up a free avatar for your email address at <a href="http://gravatar.com">http://gravatar.com</a>
              </span>
              <br /> <br />
            </div>

            <div id="email" class="tab-pane fade">
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, { class: 'form-control', autocomplete: "off" } %>
              </div>
            </div>

            <div id="password" class="tab-pane fade">

              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, { class: 'form-control', autocomplete: "off", placeholder: 'Password' } %>
              </div>
              <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, { class: 'form-control', autocomplete: "off", placeholder: 'Confirm Password' } %>
              </div>
            </div>

            <div id="notifications" class="tab-pane fade">
              <div class="form-group" 
                <% if current_user.disable_notifications? %> 
                  style="display:none" 
                <% end %>  
                id="notification_distance_group">
                <%= f.label :notification_range %> <i>This range, measured in miles, controls your range for new user notifications and local conversations.  Generally, rural areas will want larger ranges and densely populated cities will want shorter ranges.</i>
                <%= f.text_field :notification_distance, { class: 'form-control'} %>
              </div>

            </div>


          </div>
        </div>
      </div>
    </div>

  </div>


  </section>
  <section>
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-10">
        <%= f.submit "Save User", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  </section
<% end %>

app/views/findgoplayers.com/_how_it_works.html.erb
Find a player or club nearby.